### ISSUE TITLE
Access to DSP functions on TAS5825M

### ISSUE THREAD

**Issue by Glider95** [HX2003/TAS5825M-Basic#1]
Hello @HX2003,

I came across your [project ](https://hackaday.io/project/175727-tas5825m-i2s-audio-amp) as I was looking for a digital amplifier for my [WiSA Wireless Home theatre project](https://www.audiosciencereview.com/forum/index.php?threads/diy-wisa-home-theater-system.56394/#post-2077397).

This chipset and the board you have design completely fulfilled my requirements in term of size, simplicity, power output.
However, I would like to know if you ever managed to access the DSP integrated on this chip ?
For me, it would be useful to achieve an active crossover for a Mid/tweeter configuration (+ maybe room correction in the future ?)

Looking forward for your feedback,

**Comment by HX2003** [comment]
@Glider95 Hey, I did not attempt to access the DSP. It seems that the only way is to request the software from TI, and that may require the evaluation kit.
